### ISSUE TITLE
Assertion errors in plover code _sometimes_ with z͙͕̹̩̀͑ͮ̇̉ͣ̄͋̕ȃ̵̝͎̘̬͙̖̼͆ͤ̕͝ͅ l̵̤̟̜͎͍̠̭̽̿͂ͬͩ͜ģ̲͈͍̔ͩ̀ͣͬ̉ͨ̕̚͝o̴̢̓̓ͦ̈́̂̆͛ͭͣ

### ISSUE THREAD

**Issue by psethwick** [psethwick/plover_fancytext#10]
I suspect this happens when some text is replaced. `-T/-G`: th~e~ing
Would like to confirm with some unit tests

**Comment by psethwick** [comment]
2020-11-07 13:54:49,405 [Dummy-1] INFO: [Action(text='are', trailing_space=' ', word='are'), Action(prev_attach=True, prev_replace='e', text='ing', trailing_space=' ', word='aring')]
2020-11-07 13:54:49,406 [Dummy-1] ERROR: engine on_stroked failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/plover/engine.py", line 136, in run
    if func(*args, **kwargs):
  File "/usr/lib/python3.8/site-packages/plover/engine.py", line 356, in _on_stroked
    self._translator.translate(stroke)
  File "/usr/lib/python3.8/site-packages/plover/translation.py", line 205, in translate
    self.flush()
  File "/usr/lib/python3.8/site-packages/plover/translation.py", line 265, in flush
    self._output(undo, do, prev)
  File "/usr/lib/python3.8/site-packages/plover/translation.py", line 270, in _output
    callback(undo, do, prev)
  File "/usr/lib/python3.8/site-packages/plover/formatting.py", line 420, in format
    OutputHelper(self._output, self.last_output_spaces_after,
  File "/usr/lib/python3.8/site-packages/plover/formatting.py", line 533, in render
    for action in self.after.render(do, last_action):
  File "/usr/lib/python3.8/site-packages/plover/formatting.py", line 479, in render
    self._render_action(action)
  File "/usr/lib/python3.8/site-packages/plover/formatting.py", line 455, in _render_action
    assert self.appended_text.endswith(action.prev_replace)
AssertionError

**Comment by psethwick** [comment]
so... it _only_ happens when suffix folding is in effect, so -T/-G is almost always fine (well, it doesn't replace e, but no assertion errors)

I've put in a fix which makes each instance of zalgo use the same marks for the same characters. I don't love it, I prefer random random, but also, I don't like red Assertion ERROR popping up all the time either.

I'll see about a better fix in the future
